<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="4" total="7" passed="2">
  <reporter-output>
    <line>
      <![CDATA[Verify Error Message:Pass:Error message is Customer "SVD" has been successfully created.]]>
    </line>
    <line>
      <![CDATA[Verify Error Message:Pass:Error message is Customer has been successfully deleted.]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="50887" started-at="2020-02-13T01:36:14Z" finished-at="2020-02-13T01:37:05Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="50887" started-at="2020-02-13T01:36:14Z" finished-at="2020-02-13T01:37:05Z">
      <class name="com.actitime.customer.TC_Customer_Create_Valid">
        <test-method status="PASS" signature="TC_Customer_Create_Valid_Test()[pri:0, instance:com.actitime.customer.TC_Customer_Create_Valid@4dfa3a9d]" name="TC_Customer_Create_Valid_Test" duration-ms="22941" started-at="2020-02-13T01:36:42Z" finished-at="2020-02-13T01:37:05Z">
          <reporter-output>
            <line>
              <![CDATA[Verify Error Message:Pass:Error message is Customer "SVD" has been successfully created.]]>
            </line>
            <line>
              <![CDATA[Verify Error Message:Pass:Error message is Customer has been successfully deleted.]]>
            </line>
          </reporter-output>
        </test-method> <!-- TC_Customer_Create_Valid_Test -->
      </class> <!-- com.actitime.customer.TC_Customer_Create_Valid -->
      <class name="com.actitime.loginlogout.TC_AT_LoginLogout_Valid">
        <test-method status="PASS" signature="preCondition()[pri:0, instance:com.actitime.loginlogout.TC_AT_LoginLogout_Valid@754ba872]" name="preCondition" is-config="true" duration-ms="10263" started-at="2020-02-13T01:36:04Z" finished-at="2020-02-13T01:36:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preCondition -->
        <test-method status="PASS" signature="TC_AT_LoginLogout_ValidTest()[pri:0, instance:com.actitime.loginlogout.TC_AT_LoginLogout_Valid@754ba872]" name="TC_AT_LoginLogout_ValidTest" duration-ms="16197" started-at="2020-02-13T01:36:14Z" finished-at="2020-02-13T01:36:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_AT_LoginLogout_ValidTest -->
        <test-method status="PASS" signature="afterSuiteMethod()[pri:0, instance:com.actitime.loginlogout.TC_AT_LoginLogout_Valid@754ba872]" name="afterSuiteMethod" is-config="true" duration-ms="863" started-at="2020-02-13T01:37:05Z" finished-at="2020-02-13T01:37:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuiteMethod -->
      </class> <!-- com.actitime.loginlogout.TC_AT_LoginLogout_Valid -->
      <class name="com.actitime.loginlogout.TC_AT_LoginLogout_InValid">
        <test-method status="FAIL" signature="TC_AT_LoginLogout_InValid_Test()[pri:0, instance:com.actitime.loginlogout.TC_AT_LoginLogout_InValid@146ba0ac]" name="TC_AT_LoginLogout_InValid_Test" duration-ms="11667" started-at="2020-02-13T01:36:30Z" finished-at="2020-02-13T01:36:42Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at com.actitime.loginlogout.TC_AT_LoginLogout_InValid.TC_AT_LoginLogout_InValid_Test(TC_AT_LoginLogout_InValid.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_AT_LoginLogout_InValid_Test -->
      </class> <!-- com.actitime.loginlogout.TC_AT_LoginLogout_InValid -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
